# Generated by Django 5.2.8 on 2025-11-10 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_conta', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriçao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('e_Credito', models.BooleanField(default=False)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=256)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renda_variavel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='transacao',
            fields=[
                ('id_transacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.conta')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoRecorrente',
            fields=[
                ('id_recorrente', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=10)),
                ('proximoa_data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.conta')),
            ],
        ),
        migrations.CreateModel(
            name='orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField(blank=True, default=django.utils.timezone.now, null=True)),
                ('gasto_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_meta', models.CharField(max_length=100)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inicio_meta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_alvo', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario'),
        ),
    ]
