# Generated by Django 5.2.8 on 2025-11-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_alter_usuario_renda_mensal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacaorecorrente',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='transacaorecorrente',
            name='id_conta',
        ),
        migrations.DeleteModel(
            name='orcamento',
        ),
        migrations.DeleteModel(
            name='TransacaoRecorrente',
        ),
    ]
